'use strict';
const CONFIG={W:1920,H:1080,CRUISE:110,MIN:71.5,MAX:181.5,ACCEL:105,BRAKE:165,RETURN:26,PIXELS_PER_KMH:4.5,STEER_SPEED:1.05,RECOVERY:1.8,HEALTH:4,SPAWN_START:2.9,SPAWN_MIN:1.5,PARALLAX:[.025,.2,.55,1],LANES:[895,965,1035]};
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;
const raw=[
['Redline','Sportkupé',0,78,500,208,[[99,232,28],[388,233,28]]],
['Alpine','Kompakt hatchback',0,300,497,211,[[86,453,28],[389,453,28]]],
['Graphite','Városi SUV',0,523,502,215,[[101,680,29],[405,680,29]]],
['Cobalt','Sport szedán',0,752,510,199,[[104,891,29],[412,891,29]]],
['Evergreen','Performance kombi',500,78,503,209,[[601,232,29],[906,232,29]]],
['Ember','Crossover',497,293,506,219,[[598,454,29],[906,454,29]]],
['Silverline','Elektromos fastback',501,535,511,203,[[604,682,29],[917,682,29]]],
['Solar','Sportautó',506,758,514,195,[[608,889,29],[920,889,29]]],
['Batmobile','Gotham / 1989',1001,98,535,192,[[1110,231,29],[1438,234,27]]],
['DeLorean','Időgép / 1985',1001,300,535,219,[[1102,462,29],[1420,461,29]]],
['Maserati','GranTurismo',1014,536,522,202,[[1119,683,29],[1440,683,29]]]
];
let assets={},cars=[],selected=8,mode='loading',keys=new Set(),touchKeys=new Set(),traffic=[],distance=0,score=0,health=4,speed=110,position=.45,steerVelocity=0,steerParallax=0,scroll=0,wheelAngle=0,recovery=0,spawnClock=2.8,time=0,last=0,toastTimer=0,shake=0,nearMisses=0;
function makeCanvas(w,h){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
function loadImage(name){return new Promise((resolve,reject)=>{let im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error(name+' nem tölthető be'));im.src='assets/'+name+'.png'})}
function sprite(data){const [name,type,x,y,w,h,wheels]=data;let c=makeCanvas(w,h),g=c.getContext('2d');g.imageSmoothingEnabled=false;g.drawImage(assets.cars,x,y,w,h,0,0,w,h);const image=g.getImageData(0,0,w,h);let l=w,t=h,r=0,b=0;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++)if(image.data[(yy*w+xx)*4+3]>180){l=Math.min(l,xx);r=Math.max(r,xx);t=Math.min(t,yy);b=Math.max(b,yy)}l=Math.max(0,l-2);t=Math.max(0,t-2);r=Math.min(w,r+3);b=Math.min(h,b+3);let crop=makeCanvas(r-l,b-t);crop.getContext('2d').drawImage(c,l,t,r-l,b-t,0,0,r-l,b-t);return {name,type,img:crop,wheels:wheels.map(([wx,wy,rad])=>({x:wx-x-l,y:wy-y-t,r:rad}))}}
function drawCar(g,index,x,bottom,width,angle=0,police=false,alpha=1){const car=cars[index];if(!car)return;const ratio=width/car.img.width,h=car.img.height*ratio;g.save();g.globalAlpha=alpha;g.imageSmoothingEnabled=false;g.drawImage(car.img,Math.round(x),Math.round(bottom-h),Math.round(width),Math.round(h));for(const w of car.wheels){const cx=x+w.x*ratio,cy=bottom-h+w.y*ratio,rad=w.r*ratio;g.save();g.beginPath();g.arc(cx,cy,rad,0,Math.PI*2);g.clip();g.translate(cx,cy);g.rotate(angle);g.drawImage(car.img,w.x-w.r,w.y-w.r,w.r*2,w.r*2,-rad,-rad,rad*2,rad*2);g.restore()}if(police){let roofX=x+width*.46,roofY=bottom-h+5;g.fillStyle='#071020';g.fillRect(roofX-2,roofY-8,35,9);g.fillStyle=Math.floor(time*8)%2?'#ff3159':'#731529';g.fillRect(roofX,roofY-7,14,6);g.fillStyle=Math.floor(time*8)%2?'#163e75':'#40cfff';g.fillRect(roofX+17,roofY-7,14,6);g.font='bold 11px monospace';g.fillStyle='#f3f5ef';g.fillText('POLICE',x+width*.42,bottom-h*.35)}g.restore()}
function selectCar(index){selected=Math.max(0,Math.min(cars.length-1,index));$('carName').textContent=cars[selected].name;$('carType').textContent=cars[selected].type;$('carIndex').textContent=String(selected+1).padStart(2,'0')+' / 11';[...$('carList').children].forEach((b,i)=>b.setAttribute('aria-pressed',String(i===selected)));let g=$('heroCar').getContext('2d');g.clearRect(0,0,820,300);drawCar(g,selected,35,255,750,0)}
function setMode(next){mode=next;keys.clear();touchKeys.clear();steerVelocity=0;$('garage').hidden=next!=='garage';$('shade').hidden=next!=='garage';$('footer').hidden=next!=='garage';$('hud').hidden=!['playing','paused','over'].includes(next);$('pause').hidden=next!=='playing';$('touch').hidden=next!=='playing';$('overlay').hidden=!['paused','over'].includes(next)}
function start(){if(!cars.length)return;traffic=[];distance=0;score=0;health=CONFIG.HEALTH;speed=CONFIG.CRUISE;position=.45;steerVelocity=0;steerParallax=0;recovery=0;spawnClock=3.1;nearMisses=0;setMode('playing');toast('KERÜLD KI A FORGALMAT',2.5)}
function pause(){if(mode!=='playing')return;setMode('paused');$('overlayTag').textContent='PIHENŐ';$('overlayTitle').textContent='Szünet.';$('overlayText').textContent='Az éjszaka megvár.';$('resume').textContent='FOLYTATÁS'}
function gameOver(){setMode('over');$('overlayTag').textContent='FUTAM VÉGE';$('overlayTitle').textContent='Még egy kör?';$('overlayText').textContent=(distance/1000).toFixed(2)+' km · '+Math.floor(score)+' pont';$('resume').textContent='ÚJRAINDÍTÁS'}
function toast(s,d=1.5){$('toast').textContent=s;toastTimer=d}
function held(key){return keys.has(key)||touchKeys.has(key)}
function moveToward(a,b,step){return a<b?Math.min(b,a+step):Math.max(b,a-step)}
function player(){return {x:260+position*550,y:CONFIG.LANES[0]+position*(CONFIG.LANES[2]-CONFIG.LANES[0]),width:selected===8?300:245,index:selected}}
function spawn(){const level=Math.min(distance/5000,1),police=Math.random()<.08+level*.1,fast=Math.random()<.22,lane=Math.floor(Math.random()*3);const v=fast?CONFIG.MAX+18+Math.random()*22:35+Math.random()*28;const x=fast?-420:CONFIG.W+400; if(traffic.some(t=>Math.abs(t.x-x)<650&&Math.abs(t.y-CONFIG.LANES[lane])<80))return;traffic.push({x,y:CONFIG.LANES[lane],lane,index:police?1:Math.floor(Math.random()*cars.length),width:police?245:225+Math.random()*25,v,police,passed:false,angle:Math.random()*6,age:0,adjusted:false})}
function update(dt){time+=dt;if(toastTimer>0){toastTimer-=dt;if(toastTimer<=0)$('toast').textContent=''}if(mode==='garage'){scroll+=50*dt;return}if(mode!=='playing')return;let target=held('ArrowLeft')?CONFIG.MIN:held('ArrowRight')?CONFIG.MAX:CONFIG.CRUISE;speed=moveToward(speed,target,(target<speed?CONFIG.BRAKE:target===CONFIG.MAX?CONFIG.ACCEL:CONFIG.RETURN)*dt);if(recovery>0)recovery=Math.max(0,recovery-dt);const direction=(held('ArrowDown')?1:0)-(held('ArrowUp')?1:0);steerVelocity=direction*CONFIG.STEER_SPEED;position=Math.max(0,Math.min(1,position+steerVelocity*dt));steerParallax+=((position-.45)*18-steerParallax)*(-Math.expm1(-dt/0.025));const travel=speed*CONFIG.PIXELS_PER_KMH*dt;scroll+=travel;wheelAngle+=travel/32;distance+=speed/3.6*dt;score+=speed/3.6*dt*.8;spawnClock-=dt;if(spawnClock<=0){spawn();spawnClock=Math.max(CONFIG.SPAWN_MIN,CONFIG.SPAWN_START-distance/5000)+Math.random()*.6}const p=player();for(const t of traffic){t.age+=dt;t.x+=(t.v-speed)*CONFIG.PIXELS_PER_KMH*dt;t.angle+=t.v*dt*.1;if(t.police&&!t.adjusted&&t.x>p.x+600&&t.x<1500){t.lane=Math.round(position*2);t.adjusted=true}t.y=moveToward(t.y,CONFIG.LANES[t.lane],t.police?23*dt:0);let dx=Math.abs(t.x+t.width/2-(p.x+p.width/2)),dy=Math.abs(t.y-p.y);if(recovery===0&&dx<(p.width+t.width)*.36&&dy<28){health--;recovery=CONFIG.RECOVERY;speed=CONFIG.MIN;shake=.25;toast(health?'ÜTKÖZÉS · −1 ÁLLAPOT':'FUTAM VÉGE');if(health<=0){gameOver();break}}if(!t.passed&&t.x+t.width<p.x){t.passed=true;score+=t.police?120:50;if(dy>=28&&dy<60){score+=100;nearMisses++;toast('SZŰK ELŐZÉS +100')}}}traffic=traffic.filter(t=>t.x>-650&&t.x<CONFIG.W+800);shake=Math.max(0,shake-dt);$('speed').innerHTML=Math.round(speed)+' <em>km/h</em>';$('speedMeter').style.width=((speed-CONFIG.MIN)/(CONFIG.MAX-CONFIG.MIN)*100)+'%';$('distance').innerHTML=(distance/1000).toFixed(2)+' <em>km</em>';$('score').textContent=String(Math.floor(score)).padStart(5,'0');$('health').textContent='● '.repeat(health)+'○ '.repeat(CONFIG.HEALTH-health)}
// Ping-pong tiles share identical edge pixels and never reveal a gap.
function layer(im,y,h,factor,sy=0,sh=im.height){const width=im.width*h/sh,offset=(((scroll+steerParallax)*factor)%(width*2)+width*2)%(width*2),start=Math.floor(offset/width);for(let n=start;n<start+Math.ceil(CONFIG.W/width)+2;n++){let x=n*width-offset;ctx.save();ctx.translate(Math.round(x),Math.round(y));if(n%2){ctx.translate(Math.ceil(width),0);ctx.scale(-1,1)}ctx.drawImage(im,0,sy,im.width,sh,0,0,Math.ceil(width)+1,Math.ceil(h));ctx.restore()}}
function render(){ctx.clearRect(0,0,CONFIG.W,CONFIG.H);ctx.fillStyle='#061023';ctx.fillRect(0,0,CONFIG.W,CONFIG.H);if(!assets.sky)return;ctx.save();if(shake>0)ctx.translate(Math.sin(time*95)*5*shake/.25,Math.cos(time*83)*3*shake/.25);layer(assets.sky,0,850,CONFIG.PARALLAX[0]);layer(assets.skyline,100,725,CONFIG.PARALLAX[1]);layer(assets.buildings,170,700,CONFIG.PARALLAX[2]);layer(assets.road,825,255,CONFIG.PARALLAX[3],440,242);if(mode!=='garage'&&mode!=='loading'){const p=player();const all=traffic.map(t=>({...t,isPlayer:false}));all.push({...p,isPlayer:true,angle:wheelAngle});all.sort((a,b)=>a.y-b.y||Number(a.isPlayer)-Number(b.isPlayer));for(const t of all){drawCar(ctx,t.index,t.x,t.y,t.width,t.angle,t.police,t.isPlayer&&recovery>0&&Math.floor(time*12)%2?.55:1);if(t.isPlayer){ctx.fillStyle='#ffcb66';ctx.beginPath();ctx.moveTo(t.x+t.width/2-7,t.y-115);ctx.lineTo(t.x+t.width/2+7,t.y-115);ctx.lineTo(t.x+t.width/2,t.y-106);ctx.fill()}}}ctx.restore()}
function frame(stamp){const dt=Math.min((stamp-last)/1000||0,1/30);last=stamp;update(dt);render();requestAnimationFrame(frame)}
document.addEventListener('keydown',e=>{if(e.key.startsWith('Arrow')||e.key===' '){e.preventDefault();if(mode==='playing')keys.add(e.key)}if(e.key==='Escape'&&!e.repeat){if(mode==='playing')pause();else if(mode==='paused')setMode('playing')}if(e.key==='Enter'&&mode==='garage')start()});document.addEventListener('keyup',e=>keys.delete(e.key));window.addEventListener('blur',()=>{keys.clear();touchKeys.clear();steerVelocity=0;pause()});document.addEventListener('visibilitychange',()=>{if(document.hidden){keys.clear();touchKeys.clear();steerVelocity=0;pause()}});$('start').onclick=start;$('pause').onclick=pause;$('resume').onclick=()=>mode==='over'?start():setMode('playing');$('back').onclick=()=>{setMode('garage');$('toast').textContent=''};document.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();if(mode!=='playing')return;b.setPointerCapture(e.pointerId);touchKeys.add(b.dataset.key)};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>touchKeys.delete(b.dataset.key)});
async function boot(){try{const names=['sky','skyline','buildings','road','cars'];const images=await Promise.all(names.map(loadImage));names.forEach((n,i)=>assets[n]=images[i]);cars=raw.map(sprite);cars.forEach((car,i)=>{const b=document.createElement('button');b.className='carButton';b.setAttribute('aria-label',car.name+' kiválasztása');b.title=car.name;b.onclick=()=>selectCar(i);const c=makeCanvas(200,80);drawCar(c.getContext('2d'),i,4,70,192);b.append(c);const label=document.createElement('small');label.textContent=String(i+1).padStart(2,'0');b.append(label);$('carList').append(b)});selectCar(selected);setMode('garage');$('start').disabled=false;$('start').textContent='INDULÁS';registerTools()}catch(e){$('carName').textContent='Betöltési hiba';$('carType').textContent=e.message;$('start').textContent='ÚJRATÖLTÉS';$('start').disabled=false;$('start').onclick=()=>location.reload()}requestAnimationFrame(frame)}
function registerTools(){if(!document.modelContext?.registerTool)return;const tool={name:'select_racing_car',description:'Select one of the eleven cars in the garage. Does not start a race.',inputSchema:{type:'object',properties:{carIndex:{type:'integer',minimum:0,maximum:10}},required:['carIndex'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(mode!=='garage'||!Number.isInteger(input.carIndex)||input.carIndex<0||input.carIndex>=cars.length)throw Error('Choose a car index from 0 to 10 while in the garage.');selectCar(input.carIndex);return {selected:cars[selected].name}}};try{Promise.resolve(document.modelContext.registerTool(tool)).catch(()=>{})}catch{}}
window.neonDrive={getState:()=>({mode,selected,speed,distance,score,health,position,trafficCount:traffic.length}),start,pause,selectCar};boot();
